FIX: Test regressions with current core
```
not ok 2 Chrome 116.0 - [undefined ms] - Global error: Uncaught TypeError: this.send is not a function at http://localhost:7357/assets/plugins/discourse-codebytes-plugin.js, line 222
```